project:
  type: website

website:
  title: "Beyond Significance"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.md
      - chap1.qmd
      - chap2.qmd
      - chap3.qmd
      - chap4.qmd
      - chap5.qmd
      - chap6.qmd

execute:
  enabled: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    filters:
      - shinylive