project:
  type: website

website:
  title: "Beyond Significance"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.md
      - chap1.md
      - chap2.md
      - chap3.md
      - chap4.md
      - chap5.md
      - chap6.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    filters:
      - shinylive